name: pokeapp
description: ZipDev Challenge.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  #Offline images
  cached_network_image: ^2.0.0
  #Equality Values
  equatable: ^1.2.5
  #Functional Programming
  dartz: ^0.9.1
  #State Management
  provider: any
  #HTTP
  http: any
  #Local Storage
  shared_preferences: ^0.5.12
  #Onboarding Pages
  introduction_screen: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/elmarco.png

  uses-material-design: true
